### ISSUE TITLE
User Manual not updated since ~3 weeks ago

### ISSUE THREAD

**Issue by phile314** [agda/agda#1935]
The user manual is stuck at commit 0187c0ce . Error message from readthedocs.org:

<pre>
 Running Sphinx v1.3.5
making output directory...

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/agda/envs/latest/lib/python3.4/site-packages/sphinx/application.py", line 431, in setup_extension
    mod = __import__(extension, None, None, ['setup'])
ImportError: No module named 'sphinx.ext.imgmath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/agda/envs/latest/lib/python3.4/site-packages/sphinx/cmdline.py", line 243, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/docs/checkouts/readthedocs.org/user_builds/agda/envs/latest/lib/python3.4/site-packages/sphinx/application.py", line 144, in __init__
    self.setup_extension(extension)
  File "/home/docs/checkouts/readthedocs.org/user_builds/agda/envs/latest/lib/python3.4/site-packages/sphinx/application.py", line 435, in setup_extension
    err)
sphinx.errors.ExtensionError: Could not import extension sphinx.ext.imgmath (exception: No module named 'sphinx.ext.imgmath')

Extension error:
Could not import extension sphinx.ext.imgmath (exception: No module named 'sphinx.ext.imgmath')
</pre>

**Comment by phile314** [comment]
Readthedocs.org uses Sphinx 1.3.5, but we require 1.4 (see also https://github.com/agda/agda/commit/acc9bd12b455ecfa118381cca4cd8f9522ef96c8 )

**Comment by UlfNorell** [comment]
I got this after 7c01266 (I believe). I went away after I upgraded to sphinx 1.4. @asr: was there a reason 1.3 didn't work?

**Comment by phile314** [comment]
RTD.org now uses Sphinx 1.4 and works again.

**Comment by asr** [comment]
> @asr: was there a reason 1.3 didn't work?

I'm using the `-W` option (turn warnings into errors) for building the documentation. Supporting Sphinx 1.3.6 and 1.4.1 there was a warning related to an obsolete library, so I removed the support for Sphinx 1.3.6.
