### ISSUE TITLE
The GHC backend generates code that is rejected by GHC

### ISSUE THREAD

**Issue by nad** [agda/agda#4169]
Code:
```agda
module Bug where

data D : Set where
  c : D

F : D → Set → Set
F c A = A → A

f : (d : D) (A : Set) → F d A → A → A
f c _ g = g

f′ :
  (d : D) (A : Set) (P : Set → Set) →
  ((A : Set) → F d (P A)) →
  P A → P A
f′ d A P g = f d (P A) (g A)

module _
  (id : (A : Set) → (A → A) → A → A)
  (G : Set → Set)
  where

  postulate

    g : (A : Set) → G A → G A

  g′ : (A : Set) → G A → G A
  g′ A s = g A s

  g″ : (A : Set) → G A → G A
  g″ A = id (G A) (f′ c A G g′)
```
Complaint by GHC (both 8.6.5 and 8.8.1):
```
[…]/MAlonzo/Code/Bug.hs:46:36: error:
    • Couldn't match expected type ‘GHC.Types.Any’
                  with actual type ‘t0 -> t1’
      The type variables ‘t0’, ‘t1’ are ambiguous
    • The lambda expression ‘\ v3 v4 -> coe du52 (coe v0) v4’
      has two arguments,
      but its type ‘() -> AgdaAny’ has only one
      In the second argument of ‘du26’, namely
        ‘(\ v3 v4 -> coe du52 (coe v0) v4)’
      In the third argument of ‘coe’, namely
        ‘(du26 erased (\ v3 v4 -> coe du52 (coe v0) v4))’
   |
46 |       v0 (coe v1 v2) (du26 erased (\ v3 v4 -> coe du52 (coe v0) v4))
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by nad** [comment]
This is a regression. @andreasabel, bisection points towards 2ce41740c4eaa33693cbc4a10511ec2c455295e5 ("[ #3792 ] refactored conErased to Maybe [Bool] ") and d19d527f062cc55454ead76de935f5a362888368 ("[ #3792 ] fixed faulty MAlonzo compilation of constructor applications").

**Comment by andreasabel** [comment]
An extra coercion `coerce` is needed
```haskell
   v0 (coe v1 v2) (coerce du26 erased (\ v3 v4 -> coe du52 (coe v0) v4))
```
when erased version `du26` is used.

**Comment by nad** [comment]
The following code triggers a similar error:
```agda
module _ where

import Agda.Builtin.Equality
open import Agda.Builtin.Sigma
open import Agda.Builtin.Unit
open import Agda.Primitive

data ⊥ : Set where

record R₁ a : Set (lsuc a) where
  field
    R : {A : Set a} → A → A → Set a
    r : {A : Set a} (x : A) → R x x

  P : Set a → Set a
  P A = (x y : A) → R x y

record R₂ (r : ∀ ℓ → R₁ ℓ) : Set₁ where
  field
    f :
      {X Y : Σ Set (R₁.P (r lzero))} →
      R₁.R (r (lsuc lzero)) X Y → fst X → fst Y

module M (r₁ : ∀ ℓ → R₁ ℓ) (r₂ : R₂ r₁) where

  open module R₁′ {ℓ} = R₁ (r₁ ℓ) public using (P)
  open module R₂′     = R₂ r₂     public

  ⊥-elim : {A : Set} → ⊥ → A
  ⊥-elim ()

  p : P ⊥
  p x = ⊥-elim x

open Agda.Builtin.Equality

r₁ : ∀ ℓ → R₁ ℓ
R₁.R (r₁ _) = _≡_
R₁.r (r₁ _) = λ _ → refl

r₂ : R₂ r₁
R₂.f r₂ refl x = x

open M r₁ r₂

data Unit : Set where
  unit : Unit

g : Σ Unit λ _ → P (Σ Set P) → ⊥
g = unit , λ h → f (h (⊤ , λ _ _ → refl) (⊥ , p)) tt
```
Bisection points to the same commits as before.

**Comment by nad** [comment]
The offending code:
```haskell
d126 :: MAlonzo.Code.Agda.Builtin.Sigma.T14
d126
  = coe
      MAlonzo.Code.Agda.Builtin.Sigma.C32 erased
      (coe
         (\ v0 ->
            coe
              d56 d94 (MAlonzo.Code.Agda.Builtin.Sigma.C32 erased erased)
              (MAlonzo.Code.Agda.Builtin.Sigma.C32
                 erased (\ v1 -> coe du84 (\ v2 -> coe du90) (coe d94)))
              (coe
                 v0 (MAlonzo.Code.Agda.Builtin.Sigma.C32 erased erased)
                 (MAlonzo.Code.Agda.Builtin.Sigma.C32
                    erased (\ v1 -> coe du84 (\ v2 -> coe du90) (coe d94))))
              MAlonzo.Code.Agda.Builtin.Unit.C8))
```
The problem is that the penultimate lambda abstraction should have type `AgdaAny`. @andreasabel, should your fix be applied also for constructors?

https://github.com/agda/agda/blob/cf761094d13267dc87f13527ca6af2b545136033/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L530

https://github.com/agda/agda/blob/cf761094d13267dc87f13527ca6af2b545136033/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L545-L549

https://github.com/agda/agda/blob/cf761094d13267dc87f13527ca6af2b545136033/src/full/Agda/Compiler/MAlonzo/Compiler.hs#L563

**Comment by nad** [comment]
I tried replacing the final occurrence of `coe` above with `hsCoerce`, and that did not seem to work.

**Comment by nad** [comment]
Correction: It did seem to work (after I removed an outdated file).

**Comment by nad** [comment]
The test suite is happy. Is the fix "correct"? Can one break anything by coercing more? In that case the fix does at least not break anything. However, perhaps we should add even more coercions.

**Comment by andreasabel** [comment]
> Is the fix "correct"?

I guess the way to go about discussing this question is making a PR.

Anyway, since it is not clear what harm extra coercions would do, it seems safe to push your fix.

**Comment by nad** [comment]
I've pushed the fix and the test case. Unfortunately the test case fails for the JS backend:
```
/jAgda.Issue4169-2.js:90
exports["_NameId 98 9974603751767637182"]["⊥-elim"] = exports["M"]["⊥-elim"](exports["r₁"])(exports["r₂"]);
                                                                            ^

TypeError: exports.M.⊥-elim is not a function
    at Object.<anonymous> (/jAgda.Issue4169-2.js:90:77)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
Here is the generated definition of `exports.M.⊥-elim`:
```javascript
exports["M"]["⊥-elim"] = undefined;
```
Perhaps someone who knows more about JavaScript can fix this problem. (I have disabled the test case for the JS backend.)

**Comment by UlfNorell** [comment]
Closing this and opening a new issue for the JS problem.
