### ISSUE TITLE
The GHC and JS backends do not warn about missing COMPILE pragmas

### ISSUE THREAD

**Issue by nad** [agda/agda#5422]
Both the GHC and the JS backend compile the following code without any errors:
```agda
open import Agda.Builtin.IO
open import Agda.Builtin.String
open import Agda.Builtin.Unit

postulate
  putStr : String → IO ⊤

main : IO ⊤
main = putStr "Success\n"
```
However, the resulting code does not execute correctly:
```
Bug: MAlonzo Runtime Error: postulate evaluated: Bug.putStr
CallStack (from HasCallStack):
  error, called at […]/MAlonzo/Code/Bug.hs:16:5 in main:MAlonzo.Code.Bug
```
```
[…]/jAgda.Bug.js:9
exports["main"] = exports["putStr"]("Success\n");
                                   ^

TypeError: exports.putStr is not a function
    at Object.<anonymous> ([…]/jAgda.Bug.js:9:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
I think the backends should warn about postulates without associated `COMPILE` pragmas.

**Comment by andreasabel** [comment]
I think you want some mechanism to detect whether a `postulate` is reachable during program execution.  This is in general undecidable.  
One could maybe detect some cases whether a postulate will be evaluated in all possible program executions, like in your simple case.  But I wonder what the limits of such an analysis would be and whether it is worth the effort.
With systematic use of erasure, one could maybe by default flag postulates in non-erased positions that do not have a `COMPILE` pragma.

**Comment by nad** [comment]
> I think you want some mechanism to detect whether a `postulate` is reachable during program execution. This is in general undecidable.

I stated above what I want, and that is not undecidable.

**Comment by andreasabel** [comment]
@nad
> I think the backends should warn about postulates without associated `COMPILE` pragmas.

I would think that it is not uncommon that you want to ship a product with some proof still postulated.  A warning (which can be disabled) would not hurt, though.  I would however only want to see warnings about postulates that actually end up in the compiled code.
