### ISSUE TITLE
Code should be recompiled if (certain) options change

### ISSUE THREAD

**Issue by nad** [agda/agda#5428]
I think the backend machinery should have support for recompiling things if the backend options change. Here is one example of what can go wrong:
* `M.agda`:
  ```agda
  module M where

  data Bool : Set where
    true false : Bool
  ```
* `Bug.agda`:
  ```agda
  open import Agda.Builtin.IO
  open import Agda.Builtin.String
  open import Agda.Builtin.Unit

  open import M

  if_then_else : {A : Set} → Bool → A → A → A
  if true  then t else f = t
  if false then t else f = t

  postulate
    putStr : String → IO ⊤

  {-# COMPILE JS putStr =
      s => callback => { process.stdout.write(s); callback(0); }
    #-}

  main : IO ⊤
  main =
    putStr (if false then "Failure\n" else "Success\n")
  ```
```
$ agda --no-libraries --js --js-optimize --compile-dir=JS M.agda
Checking M ([…]/M.agda).
Compiling Agda.Primitive in […]/lib/prim/Agda/Primitive.agdai to JS/./jAgda.Agda.Primitive.js
Compiling M in […]/M.agdai to JS/./jAgda.M.js
$ agda --no-libraries --js --compile-dir=JS Bug.agda
Checking Bug ([…]/Bug.agda).
Compiling Agda.Builtin.Unit in […]/lib/prim/Agda/Builtin/Unit.agdai to JS/./jAgda.Agda.Builtin.Unit.js
Compiling Agda.Builtin.IO in […]/lib/prim/Agda/Builtin/IO.agdai to JS/./jAgda.Agda.Builtin.IO.js
Compiling Agda.Builtin.Bool in […]/lib/prim/Agda/Builtin/Bool.agdai to JS/./jAgda.Agda.Builtin.Bool.js
Compiling Agda.Builtin.Nat in […]/lib/prim/Agda/Builtin/Nat.agdai to JS/./jAgda.Agda.Builtin.Nat.js
Compiling Agda.Builtin.Char in […]/lib/prim/Agda/Builtin/Char.agdai to JS/./jAgda.Agda.Builtin.Char.js
Compiling Agda.Builtin.List in […]/lib/prim/Agda/Builtin/List.agdai to JS/./jAgda.Agda.Builtin.List.js
Compiling Agda.Builtin.Maybe in […]/lib/prim/Agda/Builtin/Maybe.agdai to JS/./jAgda.Agda.Builtin.Maybe.js
Compiling Agda.Builtin.Sigma in […]/lib/prim/Agda/Builtin/Sigma.agdai to JS/./jAgda.Agda.Builtin.Sigma.js
Compiling Agda.Builtin.String in […]/lib/prim/Agda/Builtin/String.agdai to JS/./jAgda.Agda.Builtin.String.js
Compiling Bug in […]/Bug.agdai to JS/./jAgda.Bug.js
$ NODE_PATH=JS node JS/jAgda.Bug.js
[…]/JS/jAgda.M.js:7
exports["Bool"]["false"] = a => a[1/* false */]();
                                               ^

TypeError: a[1] is not a function
    at exports.Bool.false.a ([…]/JS/jAgda.M.js:7:48)
    at c ([…]/JS/jAgda.Bug.js:9:42)
    at Object.<anonymous> ([…]/JS/jAgda.Bug.js:12:69)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```

**Comment by gallais** [comment]
AFAICT it's even worse than that: we seem to purely rely on module names to decide whether
to compile something. In https://github.com/agda/agda-stdlib/pull/1518 I am using a shared `--compile-dir`
to cache some of the dependencies and because all of my executables are called `Main.agda`,
I need to actively remove the generated `Main.hs` & friends in between runs otherwise agda
just skips code generation and I end up running the same executable again & again!

**Comment by nad** [comment]
Related: #3985.
