### ISSUE TITLE
null ⊔ null

### ISSUE THREAD

**Issue by nad** [agda/agda#5635]
The JS backend does not compile a certain piece of code correctly. I had trouble constructing a small test case, but the problem can be reproduced in the following way (with Agda 2.6.3-53c08b5):
```shell
git clone https://github.com/agda/agda-stdlib.git
(cd agda-stdlib && git checkout v1.7)
git clone https://github.com/nad/equality.git
(cd equality && git checkout c7a5afd36f5c6555c5a536c67409a1cff20e8e09)
printf "equality/equality.agda-lib\nagda-stdlib/standard-library.agda-lib\n" > libraries
printf "{-# OPTIONS --erased-cubical #-}\n\nopen import Equality.Path\nopen import Prelude\nopen import Erased.Cubical equality-with-paths\n\ns : Very-stable-≡ Bool\ns =\n  Very-stable-≡-⊎ 0\n    (Very-stable→Very-stable-≡ 0 Very-stable-⊤)\n    (Very-stable→Very-stable-≡ 0 Very-stable-⊤)\n" > Bug.agda
agda --js --no-default-libraries --library-file=libraries --library=equality -i. Bug.agda
NODE_PATH=. nodejs jAgda.Bug.js
```
```
[…]/jAgda.Bug.js:32
      z_jAgda_Agda_Primitive["_⊔_"](null)(null)
                                   ^

TypeError: z_jAgda_Agda_Primitive._⊔_ is not a function
    at Object.<anonymous> ([…]/jAgda.Bug.js:32:36)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
Perhaps this problem can be fixed by making sure that all level expressions are erased.

**Comment by nad** [comment]
@jespercockx, I only saw now that you changed the milestone for this issue. If this issue is not fixed, then it might not make sense to claim that the JS backend supports Erased Cubical Agda. We don't have to fix the issue before the release, but I think we should revise the changelog.

**Comment by nad** [comment]
I'll disable compilation of `--erased-cubical` code in the JS backend.
