### ISSUE TITLE
Infinite constant loops at JS load time

### ISSUE THREAD

**Issue by lawcho** [agda/agda#7524]
Agda c6de41e compiles this code

```agda
{-# OPTIONS --guardedness #-}

open import Agda.Builtin.Nat

record Stream : Set where
  coinductive
  field head : Nat
  field tail : Stream
open Stream

go : Nat → Stream
go n .head = n
go n .tail = go (2 * n)

powers-of-2 : Stream
powers-of-2 = go 1
```

to this JavaScript

```javascript
import agdaRTS from "./agda-rts.mjs";

import z_jAgda_Agda_Builtin_Nat  from "./jAgda.Agda.Builtin.Nat.mjs";
import z_jAgda_Agda_Primitive  from "./jAgda.Agda.Primitive.mjs";

const exports = {};

exports["Stream"] = {};
exports["Stream"]["record"] = a => b => ({"record": c => c["record"](a,b)});
exports["Stream"]["head"] = a => a["record"]({"record": (b,c) => b});
exports["Stream"]["tail"] = a => a["record"]({"record": (b,c) => c});
exports["go"] = a => exports["Stream"]["record"](a)(
    exports["go"](
      agdaRTS.uprimIntegerMultiply(agdaRTS.primIntegerFromString("2"),a)
  ) );
exports["powers-of-2"] = exports["go"](agdaRTS.primIntegerFromString("1"));

;export default exports;
```

which loops at JS module-load time

```shellsession
$ ~/oss/agda/master/result/bin/agda --js --js-es6 bugreport.agda && node jAgda.bugreport.mjs
Checking bugreport (/tmp/tmp.BtgwAH6KyC/bugreport.agda).
Compiling bugreport in /tmp/tmp.BtgwAH6KyC/bugreport.agdai to /tmp/tmp.BtgwAH6KyC/./jAgda.bugreport.mjs
file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:11
exports["Stream"]["record"] = a => b => ({"record": c => c["record"](a,b)});
                              ^

RangeError: Maximum call stack size exceeded
    at exports.Stream.record (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:11:31)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:12:49)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:13:18)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:13:18)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:13:18)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:13:18)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:13:18)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:13:18)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:13:18)
    at exports.go (file:///tmp/tmp.BtgwAH6KyC/jAgda.bugreport.mjs:13:18)

Node.js v20.17.0
```

This is not a recent regression -- Agda 2.6.3 had this bug too:

```shellsession
$ ~/oss/agda/v2.6.3/result/bin/agda --js bugreport.agda && NODE_PATH=. node jAgda.bugreport.js
Checking bugreport (/tmp/tmp.BtgwAH6KyC/bugreport.agda).
Compiling bugreport in /tmp/tmp.BtgwAH6KyC/bugreport.agdai to /tmp/tmp.BtgwAH6KyC/./jAgda.bugreport.js
/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:7
exports["Stream"]["record"] = a => b => ({"record": c => c["record"](a,b)});
                              ^

RangeError: Maximum call stack size exceeded
    at exports.Stream.record (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:7:31)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:10:49)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:11:18)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:11:18)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:11:18)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:11:18)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:11:18)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:11:18)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:11:18)
    at exports.go (/tmp/tmp.BtgwAH6KyC/jAgda.bugreport.js:11:18)

Node.js v20.17.0
```

**Comment by lawcho** [comment]
I think this would be fixed by translating co-patterns to ordinary case splits, e.g.

```agda
------------------ Before

record R : Set where
  coinductive
  field f1 : T1
  field f2 : T2
    {- ... -}
  field fn : Tn

e : R
e .f1 = E1
e .f2 = E2
{- ... -}
e .fn = En

------------------ After

data R-fname : Set where
  f1 f2 {- ... -} fn : R-fname

R-fty : R-fname -> Set
R-fty f1 = T1
R-fty f2 = T2
   {- ... -}
R-fty fn = Tn

e : (f : R-fname) -> R-fty f
e f1 = E1
e f2 = E2
{- ... -}
e fn = En

```

Unlike co-pattern splits, ordinary case splits compile to JS lambdas:

```javascript
///////////////////////// Before

exports["e"] = exports["R"]["record"]({
  "f1": E1
  "f2": E2
  // ...
  "fn": En
  })

///////////////////////// After
exports["e"] = f => f({
  "f1": E1
  "f2": E2
  // ...
  "fn": En
  })
```

which should prevent over-evaluation at JS load-time.
